# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='parent',
            new_name='parent_directory',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='parent',
            new_name='parent_directory',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
    ]
