# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
        ('spaced_repetition', '0002_auto_20170120_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.Student'),
            preserve_default=False,
        ),
    ]
