# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0006_auto_20170201_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='name',
            field=models.CharField(default='Home', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
